version: '3'

volumes:
  medialab_local_postgres_data: {}
  medialab_local_postgres_data_backups: {}
  medialab_polls_db_data: {}
  medialab_polls_db_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: medialab_local_django
    container_name: medialab_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: medialab_production_postgres
    container_name: medialab_local_postgres
    volumes:
      - medialab_local_postgres_data:/var/lib/postgresql/data
      - medialab_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  polls:
    build: 
      context: .
      dockerfile: ./services/polls/Dockerfile
    image: medialab_polls
    container_name: medialab_polls
    volumes:
      - ./services/polls:/app
    depends_on:
      - polls_db
      - redis
    env_file:
      - ./.envs/.local/.polls
      - ./.envs/.local/.polls_db
    ports:
      - "8001:8001"
    command: /start

  polls_db:
    build:
      context: .
      dockerfile: ./compose/production/polls_db/Dockerfile
    restart: always
    image: medialab_polls_db
    container_name: medialab_polls_db
    volumes:
      - medialab_polls_db_data:/var/lib/postgresql/data
      - medialab_polls_db_data_backups:/backups
    env_file:
      - ./.envs/.local/.polls_db

  redis:
    image: redis:6
    container_name: medialab_local_redis

  celeryworker:
    <<: *django
    image: medialab_local_celeryworker
    container_name: medialab_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: medialab_local_celerybeat
    container_name: medialab_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: medialab_local_flower
    container_name: medialab_local_flower
    ports:
      - '5555:5555'
    command: /start-flower